"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 11:42:22.398760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Outputs never change after they are written. Deletes are allowed only inside a data-erasure job, which
# sets `SET LOCAL prism.allow_erasure = 'on'` (right to erasure under India's DPDP Act).
IMMUTABLE_TABLES = (
    "analysis_runs",
    "recommendations",
    "recommendation_breakdowns",
    "conflict_reports",
    "what_if_runs",
    "audit_logs",
)
FORBID_FN = """
CREATE OR REPLACE FUNCTION forbid_update_delete() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND current_setting('prism.allow_erasure', true) = 'on' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION '% is immutable: % is not allowed', TG_TABLE_NAME, TG_OP;
END;
$$ LANGUAGE plpgsql;
"""
ANALYTICS_MV = """
CREATE MATERIALIZED VIEW mv_admin_analytics AS
SELECT r.career_id, c.name AS career_name, r.affordability_class, COUNT(*) AS n
FROM recommendations r
JOIN analysis_runs a ON a.id = r.run_id AND a.kind = 'baseline'
JOIN careers c ON c.id = r.career_id
WHERE r.rank = 1
GROUP BY r.career_id, c.name, r.affordability_class
HAVING COUNT(*) >= 5;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_instruments",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "version", name="uq_instrument_code_version"),
    )
    op.create_table(
        "careers",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sector", sa.String(length=30), nullable=False),
        sa.Column(
            "steam_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("short_description", sa.String(length=300), nullable=False),
        sa.Column("typical_entry_education", sa.String(length=160), nullable=False),
        sa.Column("automation_risk", sa.Float(), nullable=False),
        sa.Column(
            "requirement_vector",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("search_keywords", sa.String(length=80), nullable=False),
        sa.Column(
            "related_exam_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "sector IN ('engineering','computing_ai','health_life_sciences','design_arts','business_finance','law_policy','education_research','media_communication','agri_environment','energy_manufacturing','aerospace_mobility','hospitality_services')",
            name="ck_careers_sector",
        ),
        sa.CheckConstraint(
            "automation_risk >= 0 AND automation_risk <= 1", name="ck_careers_automation_risk_unit"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("careers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_careers_sector"), ["sector"], unique=False)

    op.create_table(
        "dataset_versions",
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "counts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "exams",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("conducting_body", sa.String(length=120), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("frequency", sa.String(length=30), nullable=False),
        sa.Column("eligibility_summary", sa.String(length=300), nullable=False),
        sa.Column("official_url", sa.String(length=300), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_exams_fact_checked",
        ),
        sa.CheckConstraint("verification <> 'disputed' OR is_estimate", name="ck_exams_disputed_estimate"),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_exams_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')", name="ck_exams_verification"
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_exams_confidence"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exams_dataset_version_id"), ["dataset_version_id"], unique=False)

    op.create_table(
        "regions",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=False),
        sa.Column("type", sa.String(length=14), nullable=False),
        sa.Column("cost_of_living_index", sa.Float(), nullable=False),
        sa.Column("salary_multiplier", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('metro','tier2','tier3','rural','international')", name="ck_regions_type"
        ),
        sa.CheckConstraint("cost_of_living_index > 0", name="ck_regions_col"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "scholarships",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=160), nullable=False),
        sa.Column("provider_type", sa.String(length=16), nullable=False),
        sa.Column("amount_type", sa.String(length=16), nullable=False),
        sa.Column("amount_per_year", sa.Integer(), nullable=False),
        sa.Column(
            "year_amounts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("percent_of_tuition", sa.Float(), nullable=True),
        sa.Column("max_years", sa.Integer(), nullable=False),
        sa.Column(
            "covers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "eligibility_rules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("eligibility_summary", sa.String(length=400), nullable=False),
        sa.Column("self_declared_criteria", sa.String(length=300), nullable=True),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("stackable", sa.Boolean(), nullable=False),
        sa.Column("exclusive_group", sa.String(length=40), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("deadline_status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "amount_type IN ('fixed','percent_tuition','full_tuition')", name="ck_scholarships_type"
        ),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_scholarships_fact_checked",
        ),
        sa.CheckConstraint(
            "verification <> 'disputed' OR is_estimate", name="ck_scholarships_disputed_estimate"
        ),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_scholarships_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')",
            name="ck_scholarships_verification",
        ),
        sa.CheckConstraint("amount_per_year > 0", name="ck_scholarships_amount"),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_scholarships_confidence"),
        sa.CheckConstraint("probability >= 0 AND probability <= 1", name="ck_scholarships_probability_unit"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("scholarships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scholarships_dataset_version_id"), ["dataset_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scholarships_deadline"), ["deadline"], unique=False)

    op.create_table(
        "scoring_configs",
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column(
            "weights",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("preferred_language", sa.String(length=8), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('student','parent','educator','admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "assessment_submissions",
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("instrument_id", sa.String(length=36), nullable=False),
        sa.Column("client_submission_id", sa.String(length=64), nullable=True),
        sa.Column(
            "flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("answered", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["assessment_instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "instrument_id", name="uq_submissions_id_instrument"),
        sa.UniqueConstraint("student_user_id", "client_submission_id", name="uq_submissions_client_id"),
    )
    with op.batch_alter_table("assessment_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assessment_submissions_student_user_id"), ["student_user_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)

    op.create_table(
        "career_edges",
        sa.Column("from_career_id", sa.String(length=36), nullable=False),
        sa.Column("to_career_id", sa.String(length=36), nullable=False),
        sa.Column("skill_overlap", sa.Float(), nullable=False),
        sa.Column("transition_difficulty", sa.Float(), nullable=False),
        sa.Column("why", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("from_career_id <> to_career_id", name="ck_career_edges_not_self"),
        sa.CheckConstraint(
            "skill_overlap >= 0 AND skill_overlap <= 1", name="ck_career_edges_skill_overlap_unit"
        ),
        sa.CheckConstraint(
            "transition_difficulty >= 0 AND transition_difficulty <= 1",
            name="ck_career_edges_transition_difficulty_unit",
        ),
        sa.ForeignKeyConstraint(["from_career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_career_id", "to_career_id", name="uq_career_edges"),
    )
    with op.batch_alter_table("career_edges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_career_edges_from_career_id"), ["from_career_id"], unique=False)

    op.create_table(
        "career_skills",
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("skill", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(length=12), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("importance >= 0 AND importance <= 1", name="ck_career_skills_importance_unit"),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("career_id", "skill", name="uq_career_skills"),
    )
    with op.batch_alter_table("career_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_career_skills_career_id"), ["career_id"], unique=False)

    op.create_table(
        "data_refresh_jobs",
        sa.Column("triggered_by", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column(
            "counts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "educator_assignments",
        sa.Column("educator_user_id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("school_name", sa.String(length=160), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["educator_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("educator_user_id", "student_user_id", name="uq_educator_student"),
    )
    with op.batch_alter_table("educator_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_educator_assignments_educator_user_id"), ["educator_user_id"], unique=False
        )

    op.create_table(
        "exam_sessions",
        sa.Column("exam_id", sa.String(length=36), nullable=False),
        sa.Column("cycle_year", sa.Integer(), nullable=False),
        sa.Column("session_no", sa.Integer(), nullable=False),
        sa.Column("registration_close", sa.Date(), nullable=True),
        sa.Column("registration_status", sa.String(length=10), nullable=False),
        sa.Column("exam_start", sa.Date(), nullable=True),
        sa.Column("exam_end", sa.Date(), nullable=True),
        sa.Column("exam_date_status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "exam_start IS NULL OR exam_end IS NULL OR exam_start <= exam_end", name="ck_exam_sessions_dates"
        ),
        sa.CheckConstraint(
            "registration_close IS NULL OR exam_start IS NULL OR registration_close <= exam_start",
            name="ck_exam_sessions_order",
        ),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "cycle_year", "session_no", name="uq_exam_sessions"),
    )
    with op.batch_alter_table("exam_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exam_sessions_exam_id"), ["exam_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_exam_sessions_registration_close"), ["registration_close"], unique=False
        )

    op.create_table(
        "families",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institutions",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("ownership", sa.String(length=10), nullable=False),
        sa.Column("ranking_source", sa.String(length=60), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("tier BETWEEN 1 AND 4", name="ck_institutions_tier"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "local_opportunities",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("problem_statement", sa.String(length=600), nullable=False),
        sa.Column("district", sa.String(length=80), nullable=False),
        sa.Column(
            "pincodes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "steam_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("partner_type", sa.String(length=60), nullable=False),
        sa.Column("starter_project", sa.String(length=400), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_local_opportunities_fact_checked",
        ),
        sa.CheckConstraint(
            "verification <> 'disputed' OR is_estimate", name="ck_local_opportunities_disputed_estimate"
        ),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_local_opportunities_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')",
            name="ck_local_opportunities_verification",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_local_opportunities_confidence"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("local_opportunities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_local_opportunities_dataset_version_id"), ["dataset_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_local_opportunities_region_id"), ["region_id"], unique=False)

    op.create_table(
        "market_signals",
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("period", sa.String(length=8), nullable=False),
        sa.Column("demand_index", sa.Float(), nullable=False),
        sa.Column("job_velocity", sa.Float(), nullable=False),
        sa.Column("disruption_risk", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_market_signals_fact_checked",
        ),
        sa.CheckConstraint(
            "verification <> 'disputed' OR is_estimate", name="ck_market_signals_disputed_estimate"
        ),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_market_signals_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')",
            name="ck_market_signals_verification",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_market_signals_confidence"),
        sa.CheckConstraint(
            "demand_index >= 0 AND demand_index <= 1", name="ck_market_signals_demand_index_unit"
        ),
        sa.CheckConstraint(
            "disruption_risk >= 0 AND disruption_risk <= 1", name="ck_market_signals_disruption_risk_unit"
        ),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_id", "region_id", "period", "source_name", "dataset_version_id", name="uq_market_signals"
        ),
    )
    with op.batch_alter_table("market_signals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_market_signals_dataset_version_id"), ["dataset_version_id"], unique=False
        )
        batch_op.create_index("ix_market_signals_lookup", ["career_id", "region_id", "period"], unique=False)

    op.create_table(
        "mentors",
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("district", sa.String(length=80), nullable=False),
        sa.Column("organisation", sa.String(length=120), nullable=True),
        sa.Column(
            "languages",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("bio", sa.String(length=400), nullable=False),
        sa.Column("consent_on", sa.Date(), nullable=False),
        sa.Column("verified_by", sa.String(length=80), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mentors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mentors_career_id"), ["career_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mentors_region_id"), ["region_id"], unique=False)

    op.create_table(
        "pincode_regions",
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column("district", sa.String(length=80), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("pincode"),
    )
    with op.batch_alter_table("pincode_regions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pincode_regions_district"), ["district"], unique=False)

    op.create_table(
        "posting_snapshots",
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("region_code", sa.String(length=20), nullable=False),
        sa.Column("fetched_on", sa.Date(), nullable=False),
        sa.Column("posting_count", sa.Integer(), nullable=False),
        sa.Column("mean_salary", sa.Float(), nullable=True),
        sa.Column("query", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("career_id", "region_code", "fetched_on", name="uq_posting_snapshots"),
    )
    op.create_table(
        "questions",
        sa.Column("instrument_id", sa.String(length=36), nullable=False),
        sa.Column("bank_id", sa.String(length=60), nullable=False),
        sa.Column("public_id", sa.String(length=20), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("prompt", sa.String(length=400), nullable=False),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("correct_key", sa.String(length=2), nullable=True),
        sa.Column("difficulty", sa.String(length=8), nullable=True),
        sa.Column("reverse_scored", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "dimension IN ('riasec_r','riasec_i','riasec_a','riasec_s','riasec_e','riasec_c','apt_numerical','apt_verbal','apt_logical','apt_spatial','cog_analytical','cog_creative','cog_practical','val_security','val_autonomy','val_impact','val_financial','grit','risk_tolerance')",
            name="ck_questions_dimension",
        ),
        sa.CheckConstraint("type IN ('likert5','mcq')", name="ck_questions_type"),
        sa.ForeignKeyConstraint(["instrument_id"], ["assessment_instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_id"),
        sa.UniqueConstraint("id", "instrument_id", name="uq_questions_id_instrument"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_family", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_token_family"), ["token_family"], unique=False)
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("ref_id", sa.String(length=60), nullable=False),
        sa.Column("due", sa.Date(), nullable=False),
        sa.Column("send_on", sa.Date(), nullable=False),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('sms','whatsapp','email','calendar')", name="ck_reminders_channel"),
        sa.CheckConstraint("status IN ('pending','sent','failed','cancelled')", name="ck_reminders_status"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ref_id", "due", "channel", name="uq_reminders_once"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index("ix_reminders_pending", ["status", "send_on"], unique=False)

    op.create_table(
        "salary_bands",
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("entry_p50", sa.Integer(), nullable=False),
        sa.Column("mid_p50", sa.Integer(), nullable=False),
        sa.Column("senior_p50", sa.Integer(), nullable=False),
        sa.Column("growth_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_salary_bands_fact_checked",
        ),
        sa.CheckConstraint(
            "verification <> 'disputed' OR is_estimate", name="ck_salary_bands_disputed_estimate"
        ),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_salary_bands_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')",
            name="ck_salary_bands_verification",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_salary_bands_confidence"),
        sa.CheckConstraint("entry_p50 <= mid_p50 AND mid_p50 <= senior_p50", name="ck_salary_bands_order"),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("career_id", "region_id", "dataset_version_id", name="uq_salary_bands"),
    )
    with op.batch_alter_table("salary_bands", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_salary_bands_career_id"), ["career_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_salary_bands_dataset_version_id"), ["dataset_version_id"], unique=False
        )

    op.create_table(
        "student_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("board", sa.String(length=40), nullable=False),
        sa.Column("stream", sa.String(length=20), nullable=True),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=80), nullable=False),
        sa.Column("region_code", sa.String(length=20), nullable=True),
        sa.Column(
            "languages",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "interests",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "extracurriculars",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recent_score_pct", sa.Float(), nullable=True),
        sa.Column(
            "preferred_regions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("willing_to_relocate", sa.Float(), nullable=False),
        sa.Column("willing_abroad", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("grade BETWEEN 8 AND 13", name="ck_student_profiles_grade"),
        sa.CheckConstraint(
            "recent_score_pct IS NULL OR recent_score_pct BETWEEN 0 AND 100", name="ck_student_profiles_score"
        ),
        sa.CheckConstraint(
            "willing_abroad >= 0 AND willing_abroad <= 1", name="ck_student_profiles_willing_abroad_unit"
        ),
        sa.CheckConstraint(
            "willing_to_relocate >= 0 AND willing_to_relocate <= 1",
            name="ck_student_profiles_willing_to_relocate_unit",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "trait_norms",
        sa.Column("instrument_id", sa.String(length=36), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("grade_band", sa.String(length=10), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column(
            "quantiles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["assessment_instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "dimension", "grade_band", name="uq_trait_norms"),
    )
    op.create_table(
        "family_finance",
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("income_band", sa.String(length=12), nullable=False),
        sa.Column("annual_income", sa.Integer(), nullable=True),
        sa.Column("income_growth_rate", sa.Float(), nullable=False),
        sa.Column("allocatable_savings", sa.Integer(), nullable=False),
        sa.Column("existing_debt_emi", sa.Integer(), nullable=False),
        sa.Column("dependents", sa.Integer(), nullable=False),
        sa.Column("max_affordable_emi", sa.Integer(), nullable=False),
        sa.Column("loan_tolerance", sa.Float(), nullable=False),
        sa.Column("risk_appetite", sa.Float(), nullable=False),
        sa.Column("relocation_willingness", sa.Float(), nullable=False),
        sa.Column("abroad_willingness", sa.Float(), nullable=False),
        sa.Column("time_to_earn_years", sa.Integer(), nullable=False),
        sa.Column("prestige_vs_stability", sa.String(length=10), nullable=False),
        sa.Column(
            "preferred_regions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prestige_vs_stability IN ('stability','balanced','prestige')", name="ck_family_finance_ps"
        ),
        sa.CheckConstraint(
            "abroad_willingness >= 0 AND abroad_willingness <= 1",
            name="ck_family_finance_abroad_willingness_unit",
        ),
        sa.CheckConstraint(
            "allocatable_savings >= 0 AND existing_debt_emi >= 0 AND max_affordable_emi >= 0",
            name="ck_family_finance_money",
        ),
        sa.CheckConstraint(
            "annual_income IS NULL OR max_affordable_emi + existing_debt_emi <= annual_income / 12.0",
            name="ck_family_finance_emi_vs_income",
        ),
        sa.CheckConstraint("dependents BETWEEN 0 AND 12", name="ck_family_finance_dependents"),
        sa.CheckConstraint(
            "loan_tolerance >= 0 AND loan_tolerance <= 1", name="ck_family_finance_loan_tolerance_unit"
        ),
        sa.CheckConstraint(
            "relocation_willingness >= 0 AND relocation_willingness <= 1",
            name="ck_family_finance_relocation_willingness_unit",
        ),
        sa.CheckConstraint(
            "risk_appetite >= 0 AND risk_appetite <= 1", name="ck_family_finance_risk_appetite_unit"
        ),
        sa.CheckConstraint("time_to_earn_years BETWEEN 2 AND 12", name="ck_family_finance_tte"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "version", name="uq_family_finance_version"),
    )
    with op.batch_alter_table("family_finance", schema=None) as batch_op:
        batch_op.create_index(
            "uq_family_finance_current",
            ["family_id"],
            unique=True,
            postgresql_where=sa.text("is_current"),
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "family_invites",
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("uses <= max_uses AND max_uses > 0", name="ck_family_invites_uses"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_table(
        "family_links",
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("member_role", sa.String(length=10), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("member_role IN ('student','parent','guardian')", name="ck_family_links_role"),
        sa.CheckConstraint("status IN ('active','removed')", name="ck_family_links_status"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "user_id", name="uq_family_links_member"),
    )
    with op.batch_alter_table("family_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_family_links_family_id"), ["family_id"], unique=False)
        batch_op.create_index(
            "uq_family_links_one_student_family",
            ["user_id"],
            unique=True,
            postgresql_where=sa.text("member_role = 'student' AND status = 'active'"),
            sqlite_where=sa.text("member_role = 'student' AND status = 'active'"),
        )

    op.create_table(
        "local_opportunity_careers",
        sa.Column("local_opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_opportunity_id"], ["local_opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("local_opportunity_id", "career_id"),
    )
    op.create_table(
        "parent_career_preferences",
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("parent_user_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("career_id", sa.String(length=36), nullable=True),
        sa.Column("domain", sa.String(length=30), nullable=True),
        sa.Column("note", sa.String(length=280), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(career_id IS NOT NULL) <> (domain IS NOT NULL)", name="ck_parent_pref_one_target"
        ),
        sa.CheckConstraint("rank BETWEEN 1 AND 10", name="ck_parent_pref_rank"),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "parent_user_id", "rank", name="uq_parent_pref_rank"),
    )
    with op.batch_alter_table("parent_career_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_parent_career_preferences_family_id"), ["family_id"], unique=False
        )

    op.create_table(
        "pathways",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("institution_id", sa.String(length=36), nullable=False),
        sa.Column("course", sa.String(length=120), nullable=False),
        sa.Column("degree_level", sa.String(length=12), nullable=False),
        sa.Column("duration_years", sa.Integer(), nullable=False),
        sa.Column("quota", sa.String(length=10), nullable=False),
        sa.Column("fee_academic_year", sa.Integer(), nullable=False),
        sa.Column("tuition_per_year", sa.Integer(), nullable=False),
        sa.Column("hostel_per_year", sa.Integer(), nullable=False),
        sa.Column("living_per_year", sa.Integer(), nullable=False),
        sa.Column("misc_per_year", sa.Integer(), nullable=False),
        sa.Column("course_area", sa.String(length=20), nullable=False),
        sa.Column("admission_route", sa.String(length=30), nullable=False),
        sa.Column("selectivity", sa.Float(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "is_estimate OR (verification IN ('verified','secondary') AND evidence IS NOT NULL AND verified_on IS NOT NULL)",
            name="ck_pathways_fact_checked",
        ),
        sa.CheckConstraint("quota IN ('government','management','nri','open')", name="ck_pathways_quota"),
        sa.CheckConstraint("verification <> 'disputed' OR is_estimate", name="ck_pathways_disputed_estimate"),
        sa.CheckConstraint(
            "verification <> 'verified' OR source_url IS NOT NULL", name="ck_pathways_verified_url"
        ),
        sa.CheckConstraint(
            "verification IN ('unverified','secondary','verified','disputed')",
            name="ck_pathways_verification",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_pathways_confidence"),
        sa.CheckConstraint("duration_years BETWEEN 1 AND 7", name="ck_pathways_duration"),
        sa.CheckConstraint("selectivity >= 0 AND selectivity <= 1", name="ck_pathways_selectivity_unit"),
        sa.CheckConstraint(
            "tuition_per_year >= 0 AND hostel_per_year >= 0 AND living_per_year >= 0 AND misc_per_year >= 0",
            name="ck_pathways_money",
        ),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("pathways", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pathways_dataset_version_id"), ["dataset_version_id"], unique=False
        )

    op.create_table(
        "responses",
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("instrument_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.String(length=4), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id", "instrument_id"],
            ["questions.id", "questions.instrument_id"],
            name="fk_responses_question",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id", "instrument_id"],
            ["assessment_submissions.id", "assessment_submissions.instrument_id"],
            name="fk_responses_submission",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "question_id", name="uq_responses_once"),
    )
    op.create_table(
        "trait_scores",
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("raw", sa.Float(), nullable=False),
        sa.Column("normalized", sa.Float(), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("answered", sa.Integer(), nullable=False),
        sa.Column("imputed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("normalized >= 0 AND normalized <= 1", name="ck_trait_scores_normalized_unit"),
        sa.CheckConstraint("reliability >= 0 AND reliability <= 1", name="ck_trait_scores_reliability_unit"),
        sa.ForeignKeyConstraint(["student_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["assessment_submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "dimension", name="uq_trait_scores_submission_dim"),
    )
    with op.batch_alter_table("trait_scores", schema=None) as batch_op:
        batch_op.create_index(
            "ix_trait_scores_latest", ["student_user_id", "dimension", "created_at"], unique=False
        )

    op.create_table(
        "analysis_runs",
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=True),
        sa.Column("requested_by", sa.String(length=36), nullable=True),
        sa.Column("family_finance_id", sa.String(length=36), nullable=True),
        sa.Column("scoring_config_version", sa.String(length=60), nullable=False),
        sa.Column("dataset_version", sa.String(length=60), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("parent_run_id", sa.String(length=36), nullable=True),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("input_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "input_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("conflict_index", sa.Float(), nullable=False),
        sa.Column("robustness_score", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('baseline','what_if')", name="ck_analysis_runs_kind"),
        sa.ForeignKeyConstraint(["family_finance_id"], ["family_finance.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_run_id"], ["analysis_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "parent_run_id", name="uq_analysis_runs_id_parent"),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_runs_input_hash"), ["input_hash"], unique=False)
        batch_op.create_index("ix_analysis_runs_student", ["student_user_id", "created_at"], unique=False)

    op.create_table(
        "consent_records",
        sa.Column("subject_user_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by", sa.String(length=36), nullable=False),
        sa.Column("granted_by_link_id", sa.String(length=36), nullable=True),
        sa.Column("consent_type", sa.String(length=40), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by_link_id"], ["family_links.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_consent_current", ["subject_user_id", "consent_type", "created_at"], unique=False
        )

    op.create_table(
        "pathway_careers",
        sa.Column("pathway_id", sa.String(length=36), nullable=False),
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pathway_id"], ["pathways.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pathway_id", "career_id"),
    )
    with op.batch_alter_table("pathway_careers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pathway_careers_career_id"), ["career_id"], unique=False)

    op.create_table(
        "pathway_exams",
        sa.Column("pathway_id", sa.String(length=36), nullable=False),
        sa.Column("exam_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pathway_id"], ["pathways.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pathway_id", "exam_id"),
    )
    op.create_table(
        "pathway_scholarships",
        sa.Column("pathway_id", sa.String(length=36), nullable=False),
        sa.Column("scholarship_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["pathway_id"], ["pathways.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scholarship_id"], ["scholarships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pathway_id", "scholarship_id"),
    )
    op.create_table(
        "conflict_reports",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("index", sa.Float(), nullable=False),
        sa.Column("band", sa.String(length=10), nullable=False),
        sa.Column(
            "dimensions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "outcomes",
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("chosen_career_id", sa.String(length=36), nullable=True),
        sa.Column("chosen_pathway_text", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("admitted", sa.Boolean(), nullable=True),
        sa.Column("scholarship_received", sa.Boolean(), nullable=True),
        sa.Column("satisfaction", sa.Integer(), nullable=True),
        sa.Column("followed_recommendation_rank", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('enrolled','waiting','dropped','working','other')", name="ck_outcomes_status"
        ),
        sa.CheckConstraint(
            "satisfaction IS NULL OR satisfaction BETWEEN 1 AND 5", name="ck_outcomes_satisfaction"
        ),
        sa.ForeignKeyConstraint(["chosen_career_id"], ["careers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outcomes_student_user_id"), ["student_user_id"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("career_id", sa.String(length=36), nullable=False),
        sa.Column("pathway_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("affordability_class", sa.String(length=16), nullable=False),
        sa.Column(
            "buckets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["career_id"], ["careers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pathway_id"], ["pathways.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "rank", name="uq_recommendations_rank"),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recommendations_career_id"), ["career_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendations_run_id"), ["run_id"], unique=False)

    op.create_table(
        "what_if_runs",
        sa.Column("result_run_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_run_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=True),
        sa.Column(
            "overrides",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["baseline_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["result_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("result_run_id"),
    )
    op.create_table(
        "recommendation_breakdowns",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("component", sa.String(length=20), nullable=False),
        sa.Column("raw_value", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("contribution", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recommendation_id", "component"),
    )
    # ### end Alembic commands ###

    # PostgreSQL-only guarantees (SQLite is a local-dev fallback without triggers or materialized views).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(FORBID_FN)
        for table in IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
            )
        op.execute(ANALYTICS_MV)


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_admin_analytics")
        for table in IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
        op.execute("DROP FUNCTION IF EXISTS forbid_update_delete()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation_breakdowns")
    op.drop_table("what_if_runs")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_run_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_career_id"))

    op.drop_table("recommendations")
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcomes_student_user_id"))

    op.drop_table("outcomes")
    op.drop_table("conflict_reports")
    op.drop_table("pathway_scholarships")
    op.drop_table("pathway_exams")
    with op.batch_alter_table("pathway_careers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pathway_careers_career_id"))

    op.drop_table("pathway_careers")
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.drop_index("ix_consent_current")

    op.drop_table("consent_records")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_runs_student")
        batch_op.drop_index(batch_op.f("ix_analysis_runs_input_hash"))

    op.drop_table("analysis_runs")
    with op.batch_alter_table("trait_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_trait_scores_latest")

    op.drop_table("trait_scores")
    op.drop_table("responses")
    with op.batch_alter_table("pathways", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pathways_dataset_version_id"))

    op.drop_table("pathways")
    with op.batch_alter_table("parent_career_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parent_career_preferences_family_id"))

    op.drop_table("parent_career_preferences")
    op.drop_table("local_opportunity_careers")
    with op.batch_alter_table("family_links", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_family_links_one_student_family",
            postgresql_where=sa.text("member_role = 'student' AND status = 'active'"),
            sqlite_where=sa.text("member_role = 'student' AND status = 'active'"),
        )
        batch_op.drop_index(batch_op.f("ix_family_links_family_id"))

    op.drop_table("family_links")
    op.drop_table("family_invites")
    with op.batch_alter_table("family_finance", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_family_finance_current",
            postgresql_where=sa.text("is_current"),
            sqlite_where=sa.text("is_current = 1"),
        )

    op.drop_table("family_finance")
    op.drop_table("trait_norms")
    op.drop_table("student_profiles")
    with op.batch_alter_table("salary_bands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salary_bands_dataset_version_id"))
        batch_op.drop_index(batch_op.f("ix_salary_bands_career_id"))

    op.drop_table("salary_bands")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index("ix_reminders_pending")

    op.drop_table("reminders")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_family"))

    op.drop_table("refresh_tokens")
    op.drop_table("questions")
    op.drop_table("posting_snapshots")
    with op.batch_alter_table("pincode_regions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pincode_regions_district"))

    op.drop_table("pincode_regions")
    with op.batch_alter_table("mentors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mentors_region_id"))
        batch_op.drop_index(batch_op.f("ix_mentors_career_id"))

    op.drop_table("mentors")
    with op.batch_alter_table("market_signals", schema=None) as batch_op:
        batch_op.drop_index("ix_market_signals_lookup")
        batch_op.drop_index(batch_op.f("ix_market_signals_dataset_version_id"))

    op.drop_table("market_signals")
    with op.batch_alter_table("local_opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_local_opportunities_region_id"))
        batch_op.drop_index(batch_op.f("ix_local_opportunities_dataset_version_id"))

    op.drop_table("local_opportunities")
    op.drop_table("institutions")
    op.drop_table("families")
    with op.batch_alter_table("exam_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_sessions_registration_close"))
        batch_op.drop_index(batch_op.f("ix_exam_sessions_exam_id"))

    op.drop_table("exam_sessions")
    with op.batch_alter_table("educator_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_educator_assignments_educator_user_id"))

    op.drop_table("educator_assignments")
    op.drop_table("data_refresh_jobs")
    with op.batch_alter_table("career_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_career_skills_career_id"))

    op.drop_table("career_skills")
    with op.batch_alter_table("career_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_career_edges_from_career_id"))

    op.drop_table("career_edges")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("assessment_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_submissions_student_user_id"))

    op.drop_table("assessment_submissions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("scoring_configs")
    with op.batch_alter_table("scholarships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scholarships_deadline"))
        batch_op.drop_index(batch_op.f("ix_scholarships_dataset_version_id"))

    op.drop_table("scholarships")
    op.drop_table("regions")
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exams_dataset_version_id"))

    op.drop_table("exams")
    op.drop_table("dataset_versions")
    with op.batch_alter_table("careers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_careers_sector"))

    op.drop_table("careers")
    op.drop_table("assessment_instruments")
    # ### end Alembic commands ###
