"""site tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 14:06:25.829954

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_assessments",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("region", sa.String(length=20), nullable=False),
        sa.Column("interest", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("composite", sa.Float(), nullable=False),
        sa.Column("pci", sa.Integer(), nullable=False),
        sa.Column("conflict_band", sa.String(length=10), nullable=False),
        sa.Column("capacity", sa.Float(), nullable=False),
        sa.Column("fin_gap", sa.Float(), nullable=False),
        sa.Column("top1", sa.String(length=120), nullable=False),
        sa.Column("top2", sa.String(length=120), nullable=True),
        sa.Column("top3", sa.String(length=120), nullable=True),
        sa.Column("dataset_version", sa.String(length=60), nullable=False),
        sa.Column(
            "input_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("site_assessments", schema=None) as batch_op:
        batch_op.create_index("ix_site_assessments_created", ["created_at"], unique=False)

    op.create_table(
        "site_battery_attempts",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("region", sa.String(length=20), nullable=False),
        sa.Column("interest", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("logic", sa.Float(), nullable=False),
        sa.Column("creative", sa.Float(), nullable=False),
        sa.Column("comm", sa.Float(), nullable=False),
        sa.Column("hands", sa.Float(), nullable=False),
        sa.Column("sci", sa.Float(), nullable=False),
        sa.Column("mean_aptitude", sa.Float(), nullable=False),
        sa.Column("answered", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column(
            "profile_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("site_battery_attempts", schema=None) as batch_op:
        batch_op.create_index("ix_site_battery_created", ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site_battery_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_site_battery_created")

    op.drop_table("site_battery_attempts")
    with op.batch_alter_table("site_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_site_assessments_created")

    op.drop_table("site_assessments")
    # ### end Alembic commands ###
