// One-sentence plain explanations for terms shown with <Term> / <InfoTip>. Keep them short and jargon-free.
export const GLOSSARY: Record<string, string> = {
  emi: 'EMI: the fixed amount paid every month to repay a loan.',
  roi: 'Return on investment: how much more you are likely to earn over ten years, compared with what the course costs.',
  moratorium: 'Moratorium: the period while studying (and usually one year after) when banks do not ask for loan repayments.',
  nirf: 'NIRF: the Government of India ranking of colleges and universities.',
  quota: 'Quota: the admission route. Government-quota seats cost far less than management-quota seats in the same college.',
  csis: 'CSIS: a central scheme that pays the interest during the moratorium for families earning up to ₹4.5 lakh a year.',
  vidyalaxmi: 'PM-Vidyalaxmi: collateral-free education loans for top colleges, with 3% interest relief for families earning up to ₹8 lakh.',
  conflict: 'Conflict index (0–100): how far apart the student and the parents are on field, risk, place, budget, time to earn and stability.',
  confidence: 'Confidence: how sure PRISM is about this result. It falls when inputs are estimates, out of date or missing.',
  fit: 'Fit: how well a career matches the student’s interests, abilities and values from the questionnaire.',
  affordability: 'Affordability: whether the family can fund the course with savings, income, scholarships and a manageable loan.',
  market: 'Job market: demand for this career in the places the student could work, and whether it is growing.',
  disruption: 'Automation risk: the chance that automation changes this job; it lowers the score slightly.',
  family_alignment: 'Family alignment: how close a career is to the hopes the parents entered.',
  robustness: 'Robustness: how often the top career stays first when the importance of each factor is changed by ±20%.',
  estimate: 'Estimate: a figure PRISM has not yet checked against an official source. Treat it as a guide.',
  checked: 'Checked: a figure confirmed against an official or reliable published source.',
  admission: 'Admission chance: a rough estimate of getting a seat on this route with the current scores.',
  riasec: 'Holland code: three letters for the kinds of work you enjoy most (Realistic, Investigative, Artistic, Social, Enterprising, Conventional).',
  stretch: 'Stretch goal: a strong-fit career that is hard to fund or enter today, with what could make it reachable.',
  bridge: 'Bridge career: a career that both the student and the parents rate well.',
  tentative: 'Tentative: in the official calendar but may still move.',
  announced: 'Announced: in the official information bulletin.',
  estimated: 'Estimated: not announced yet; projected from earlier years.',
}
